server:
  port: 8090
  
master:
 user:
  name: NIT-BALAKRISHNA
  email: javabybalakrishna@gmail.com
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/health
    username: root
    password: admin
  
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      
  mail:    host: smtp.gmail.com
    port: 587
    username: javabybalakrishna@gmail.com
    password: krishna@123
    properties:
     mail:
      smtp:
       starttls:
         enable: true             
